### ISSUE TITLE
Can't start server

### ISSUE THREAD

**Issue by Tzikas** [by12380/react-todo-universal#1]
Not sure what has changed or what I forget since we did it together, but cloning the repo, cd into the Server, npm install && npm start results in  
`{ "error": true }` under localhost:8080.  I swapped the credentials on the client side for the proper ones.   What did I forget?

**Comment by Tzikas** [comment]
I forgot the server also need auth0 credentials.  My bad.  :)

**Comment by by12380** [comment]
@Tzikas 
Yup! I just haven't written the doc for the server repo...
Btw, this repo has a todo-app branch that is the most up-to-date.
